### ISSUE TITLE
rake redmine:plugins:migrate Error

### ISSUE THREAD

**Issue by codyliou** [pochi/redmine-schedular#12]
rake aborted!
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/trace_
output.rb:16:in `block in trace_on': invalid byte sequence in US-ASCII (Argument
Error)
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.1.0/li
b/rake/trace_output.rb:14:in`map'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.1.0/li
b/rake/trace_output.rb:14:in `trace_on'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.1.0/li
b/rake/application.rb:340:in`trace'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.1.0/li
b/rake/application.rb:187:in `display_error_message'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.1.0/li
b/rake/application.rb:174:in`rescue in standard_exception_handling'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.1.0/li
b/rake/application.rb:165:in `standard_exception_handling'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.1.0/li
b/rake/application.rb:75:in`run'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rake-10.1.0/bi
n/rake:33:in `<top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/bin/rake:23:in`load'
        from C:/RailsInstaller/Ruby1.9.3/bin/rake:23:in `<main>'

**Comment by pochi** [comment]
This plugin needs ruby version 2.0 or higher.
Please update your ruby version.
I'm sorry that I do not write this requirements on README.md,
so I'll added requirements.
Thank you for open issues.
